const fs = require('fs');

const lines = [
"'use client';",
"",
"import { useEffect, useState } from 'react';",
"",
"export default function Home() {",
"  const [articles, setArticles] = useState([]);",
"  const [loading, setLoading] = useState(true);",
"  const [search, setSearch] = useState('');",
"  const [selectedCompany, setSelectedCompany] = useState('전체');",
"",
"  const COMPANIES = ['전체', '롯데', '신세계', '현대백화점', 'CJ', '이마트', 'SSG', '쿠팡', '컬리', '올리브영', '무신사'];",
"",
"  useEffect(() => {",
"    fetch('/api/news')",
"      .then(res => res.json())",
"      .then(data => { setArticles(data.articles); setLoading(false); });",
"  }, []);",
"",
"  const filtered = articles.filter(a => {",
"    const matchCompany = selectedCompany === '전체' || a.title.includes(selectedCompany) || (a.summary && a.summary.includes(selectedCompany));",
"    const matchSearch = search === '' || a.title.includes(search);",
"    return matchCompany && matchSearch;",
"  });",
"",
"  const fmt = (s) => { const d = new Date(s); return (d.getMonth()+1)+'/'+d.getDate()+' '+d.getHours()+':'+String(d.getMinutes()).padStart(2,'0'); };",
"",
"  return (",
"    <main className='min-h-screen bg-gray-50'>",
"      <header className='bg-white border-b sticky top-0 z-10'>",
"        <div className='max-w-6xl mx-auto px-4 py-4'>",
"          <h1 className='text-2xl font-bold'>유통업계 뉴스</h1>",
"          <p className='text-sm text-gray-500 mb-3'>백화점 · 마트 · 편의점 · 식음료 · 패션 · 뷰티</p>",
"          <input type='text' placeholder='검색...' value={search} onChange={e => setSearch(e.target.value)} className='w-full border rounded-lg px-4 py-2 text-sm mb-3' />",
"          <div className='flex gap-2 flex-wrap'>",
"            {COMPANIES.map(c => (",
"              <button key={c} onClick={() => setSelectedCompany(c)} className={selectedCompany === c ? 'px-3 py-1 rounded-full text-sm bg-gray-800 text-white' : 'px-3 py-1 rounded-full text-sm bg-gray-100 text-gray-600'}>",
"                {c}",
"              </button>",
"            ))}",
"          </div>",
"        </div>",
"      </header>",
"      <div className='max-w-6xl mx-auto px-4 py-6'>",
"        {loading ? <p className='text-gray-400'>불러오는 중...</p> : (",
"          <div className='grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4'>",
"            {filtered.map((a, i) => (",
"              <a key={i} href={a.link} target='_blank' rel='noopener noreferrer' className='bg-white rounded-xl p-4 shadow-sm border'>",
"                <div className='flex gap-2 mb-2'>",
"                  <span className='text-xs bg-blue-50 text-blue-600 px-2 py-0.5 rounded-full'>{a.source}</span>",
"                  <span className='text-xs text-gray-400'>{a.date ? fmt(a.date) : ''}</span>",
"                </div>",
"                <h2 className='text-sm font-semibold mb-1'>{a.title}</h2>",
"                <p className='text-xs text-gray-500'>{a.summary}</p>",
"              </a>",
"            ))}",
"          </div>",
"        )}",
"      </div>",
"    </main>",
"  );",
"}",
];

fs.writeFileSync('app/page.tsx', lines.join('\n'), 'utf8');
console.log('완료!');